name: An Introduction to Equilibration
category: setup
authors: ""
shortdesc: "This course looks at one of the most common methods for assessing equilibration: the calculation of RMSDs. It may be a common approach, but is it a good one? Maybe not."
longdesc: ""
